from turtle import *
import time
def snowflacke(n):
    bob = Turtle()

    if n > 1:
        bob.forward(n/3)
        bob.penup()
        bob.forward(n/3)
        bob.pendown()
        bob.forward(n/3)
        bob.left(120)
        bob.forward(n / 3)
        bob.penup()
        bob.forward(n / 3)
        bob.pendown()
        bob.forward(n / 3)
        bob.left(120)
        bob.forward(n / 3)
        bob.penup()
        bob.forward(n / 3)
        bob.pendown()
        bob.forward(n / 3)
        bob.left(120)
        bob.penup()
        bob.forward(n/2)
        bob.left(90)
        bob.forward(n / 3)
        bob.penup()
        bob.forward(n / 3)
        bob.pendown()
        bob.forward(n / 3)
        bob.left(120)
        bob.forward(n / 3)
        bob.penup()
        bob.forward(n / 3)
        bob.pendown()
        bob.forward(n / 3)
        bob.left(120)
        bob.forward(n / 3)
        bob.penup()
        bob.forward(n / 3)
        bob.pendown()
        bob.forward(n / 3)
        bob.left(120)
        bob.penup()
        time.sleep(2)
        bob.forward(n / 2)
        bob.left(120)
        snowflacke(n/2)
        #bob.left(120)
        #bob.forward(n/3)
       #time.sleep(3)
        #bob.right(60)
        #bob.forward(n/3)
        #bob.left(120)
        #bob.forward(n/3)
snowflacke(100)
input()